//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 18.11.2015 11:11:10
namespace DotNextSampleApp.DotNextRZD.PublicApi.Model
{
    /// <summary>
    /// There are no comments for TrainModelSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TrainModelSingle")]
    public partial class TrainModelSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<TrainModel>
    {
        /// <summary>
        /// Initialize a new TrainModelSingle object.
        /// </summary>
        public TrainModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TrainModelSingle object.
        /// </summary>
        public TrainModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TrainModelSingle object.
        /// </summary>
        public TrainModelSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<TrainModel> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for TrainModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("TrainModel")]
    public partial class TrainModel : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TrainModel object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="originRailwayStationId">Initial value of OriginRailwayStationId.</param>
        /// <param name="destinationRailwayStationId">Initial value of DestinationRailwayStationId.</param>
        /// <param name="scheduledTime">Initial value of ScheduledTime.</param>
        /// <param name="currentTime">Initial value of CurrentTime.</param>
        /// <param name="updatedStatus">Initial value of UpdatedStatus.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static TrainModel CreateTrainModel(int ID, 
                    int originRailwayStationId, 
                    int destinationRailwayStationId, 
                    global::System.DateTimeOffset scheduledTime, 
                    global::System.DateTimeOffset currentTime, 
                    bool updatedStatus)
        {
            TrainModel trainModel = new TrainModel();
            trainModel.Id = ID;
            trainModel.OriginRailwayStationId = originRailwayStationId;
            trainModel.DestinationRailwayStationId = destinationRailwayStationId;
            trainModel.ScheduledTime = scheduledTime;
            trainModel.CurrentTime = currentTime;
            trainModel.UpdatedStatus = updatedStatus;
            return trainModel;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property TrainNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TrainNumber")]
        public string TrainNumber
        {
            get
            {
                return this._TrainNumber;
            }
            set
            {
                this.OnTrainNumberChanging(value);
                this._TrainNumber = value;
                this.OnTrainNumberChanged();
                this.OnPropertyChanged("TrainNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _TrainNumber;
        partial void OnTrainNumberChanging(string value);
        partial void OnTrainNumberChanged();
        /// <summary>
        /// There are no comments for Property OriginRailwayStationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OriginRailwayStationId")]
        public int OriginRailwayStationId
        {
            get
            {
                return this._OriginRailwayStationId;
            }
            set
            {
                this.OnOriginRailwayStationIdChanging(value);
                this._OriginRailwayStationId = value;
                this.OnOriginRailwayStationIdChanged();
                this.OnPropertyChanged("OriginRailwayStationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _OriginRailwayStationId;
        partial void OnOriginRailwayStationIdChanging(int value);
        partial void OnOriginRailwayStationIdChanged();
        /// <summary>
        /// There are no comments for Property OriginRailwayStationName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OriginRailwayStationName")]
        public string OriginRailwayStationName
        {
            get
            {
                return this._OriginRailwayStationName;
            }
            set
            {
                this.OnOriginRailwayStationNameChanging(value);
                this._OriginRailwayStationName = value;
                this.OnOriginRailwayStationNameChanged();
                this.OnPropertyChanged("OriginRailwayStationName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _OriginRailwayStationName;
        partial void OnOriginRailwayStationNameChanging(string value);
        partial void OnOriginRailwayStationNameChanged();
        /// <summary>
        /// There are no comments for Property DestinationRailwayStationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DestinationRailwayStationId")]
        public int DestinationRailwayStationId
        {
            get
            {
                return this._DestinationRailwayStationId;
            }
            set
            {
                this.OnDestinationRailwayStationIdChanging(value);
                this._DestinationRailwayStationId = value;
                this.OnDestinationRailwayStationIdChanged();
                this.OnPropertyChanged("DestinationRailwayStationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _DestinationRailwayStationId;
        partial void OnDestinationRailwayStationIdChanging(int value);
        partial void OnDestinationRailwayStationIdChanged();
        /// <summary>
        /// There are no comments for Property DestinationRailwayStationName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DestinationRailwayStationName")]
        public string DestinationRailwayStationName
        {
            get
            {
                return this._DestinationRailwayStationName;
            }
            set
            {
                this.OnDestinationRailwayStationNameChanging(value);
                this._DestinationRailwayStationName = value;
                this.OnDestinationRailwayStationNameChanged();
                this.OnPropertyChanged("DestinationRailwayStationName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _DestinationRailwayStationName;
        partial void OnDestinationRailwayStationNameChanging(string value);
        partial void OnDestinationRailwayStationNameChanged();
        /// <summary>
        /// There are no comments for Property ScheduledTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ScheduledTime")]
        public global::System.DateTimeOffset ScheduledTime
        {
            get
            {
                return this._ScheduledTime;
            }
            set
            {
                this.OnScheduledTimeChanging(value);
                this._ScheduledTime = value;
                this.OnScheduledTimeChanged();
                this.OnPropertyChanged("ScheduledTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _ScheduledTime;
        partial void OnScheduledTimeChanging(global::System.DateTimeOffset value);
        partial void OnScheduledTimeChanged();
        /// <summary>
        /// There are no comments for Property CurrentTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrentTime")]
        public global::System.DateTimeOffset CurrentTime
        {
            get
            {
                return this._CurrentTime;
            }
            set
            {
                this.OnCurrentTimeChanging(value);
                this._CurrentTime = value;
                this.OnCurrentTimeChanged();
                this.OnPropertyChanged("CurrentTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _CurrentTime;
        partial void OnCurrentTimeChanging(global::System.DateTimeOffset value);
        partial void OnCurrentTimeChanged();
        /// <summary>
        /// There are no comments for Property StatusCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("StatusCode")]
        public string StatusCode
        {
            get
            {
                return this._StatusCode;
            }
            set
            {
                this.OnStatusCodeChanging(value);
                this._StatusCode = value;
                this.OnStatusCodeChanged();
                this.OnPropertyChanged("StatusCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _StatusCode;
        partial void OnStatusCodeChanging(string value);
        partial void OnStatusCodeChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property UpdatedStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UpdatedStatus")]
        public bool UpdatedStatus
        {
            get
            {
                return this._UpdatedStatus;
            }
            set
            {
                this.OnUpdatedStatusChanging(value);
                this._UpdatedStatus = value;
                this.OnUpdatedStatusChanged();
                this.OnPropertyChanged("UpdatedStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _UpdatedStatus;
        partial void OnUpdatedStatusChanging(bool value);
        partial void OnUpdatedStatusChanged();
        /// <summary>
        /// There are no comments for Property IsDelayed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsDelayed")]
        public global::System.Nullable<bool> IsDelayed
        {
            get
            {
                return this._IsDelayed;
            }
            set
            {
                this.OnIsDelayedChanging(value);
                this._IsDelayed = value;
                this.OnIsDelayedChanged();
                this.OnPropertyChanged("IsDelayed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<bool> _IsDelayed;
        partial void OnIsDelayedChanging(global::System.Nullable<bool> value);
        partial void OnIsDelayedChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CityModelSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CityModelSingle")]
    public partial class CityModelSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<CityModel>
    {
        /// <summary>
        /// Initialize a new CityModelSingle object.
        /// </summary>
        public CityModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CityModelSingle object.
        /// </summary>
        public CityModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CityModelSingle object.
        /// </summary>
        public CityModelSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<CityModel> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for CityModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CityModel")]
    public partial class CityModel : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CityModel object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="latitude">Initial value of Latitude.</param>
        /// <param name="longitude">Initial value of Longitude.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static CityModel CreateCityModel(int ID, decimal latitude, decimal longitude)
        {
            CityModel cityModel = new CityModel();
            cityModel.Id = ID;
            cityModel.Latitude = latitude;
            cityModel.Longitude = longitude;
            return cityModel;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Latitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Latitude")]
        public decimal Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this.OnLatitudeChanging(value);
                this._Latitude = value;
                this.OnLatitudeChanged();
                this.OnPropertyChanged("Latitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _Latitude;
        partial void OnLatitudeChanging(decimal value);
        partial void OnLatitudeChanged();
        /// <summary>
        /// There are no comments for Property Longitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Longitude")]
        public decimal Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this.OnLongitudeChanging(value);
                this._Longitude = value;
                this.OnLongitudeChanged();
                this.OnPropertyChanged("Longitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _Longitude;
        partial void OnLongitudeChanging(decimal value);
        partial void OnLongitudeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RailwayStationModelSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RailwayStationModelSingle")]
    public partial class RailwayStationModelSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RailwayStationModel>
    {
        /// <summary>
        /// Initialize a new RailwayStationModelSingle object.
        /// </summary>
        public RailwayStationModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RailwayStationModelSingle object.
        /// </summary>
        public RailwayStationModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RailwayStationModelSingle object.
        /// </summary>
        public RailwayStationModelSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RailwayStationModel> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for RailwayStationModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("RailwayStationModel")]
    public partial class RailwayStationModel : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RailwayStationModel object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="cityId">Initial value of CityId.</param>
        /// <param name="latitude">Initial value of Latitude.</param>
        /// <param name="longitude">Initial value of Longitude.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static RailwayStationModel CreateRailwayStationModel(int ID, int cityId, decimal latitude, decimal longitude)
        {
            RailwayStationModel railwayStationModel = new RailwayStationModel();
            railwayStationModel.Id = ID;
            railwayStationModel.CityId = cityId;
            railwayStationModel.Latitude = latitude;
            railwayStationModel.Longitude = longitude;
            return railwayStationModel;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Code")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CityId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CityId")]
        public int CityId
        {
            get
            {
                return this._CityId;
            }
            set
            {
                this.OnCityIdChanging(value);
                this._CityId = value;
                this.OnCityIdChanged();
                this.OnPropertyChanged("CityId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _CityId;
        partial void OnCityIdChanging(int value);
        partial void OnCityIdChanged();
        /// <summary>
        /// There are no comments for Property Latitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Latitude")]
        public decimal Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this.OnLatitudeChanging(value);
                this._Latitude = value;
                this.OnLatitudeChanged();
                this.OnPropertyChanged("Latitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _Latitude;
        partial void OnLatitudeChanging(decimal value);
        partial void OnLatitudeChanged();
        /// <summary>
        /// There are no comments for Property Longitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Longitude")]
        public decimal Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this.OnLongitudeChanging(value);
                this._Longitude = value;
                this.OnLongitudeChanged();
                this.OnPropertyChanged("Longitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _Longitude;
        partial void OnLongitudeChanging(decimal value);
        partial void OnLongitudeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModel as global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModel> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModel as global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModel> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModel as global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModel> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModel as global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModel> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModel as global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModel> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModel as global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModel> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace DotNextSampleApp.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "DotNextRZD.PublicApi.Model", "DotNextSampleApp.DotNextRZD.PublicApi.Model");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "DotNextSampleApp.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("DotNextSampleApp.DotNextRZD.PublicApi.Model", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("DotNextRZD.PublicApi.Model.", originalNameAttribute.OriginalName);
                }
                return string.Concat("DotNextRZD.PublicApi.Model.", clientType.Name);
            }
            if (clientType.Namespace.Equals("DotNextSampleApp.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Trains in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Trains")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModel> Trains
        {
            get
            {
                if ((this._Trains == null))
                {
                    this._Trains = base.CreateQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModel>("Trains");
                }
                return this._Trains;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModel> _Trains;
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Cities")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModel> Cities
        {
            get
            {
                if ((this._Cities == null))
                {
                    this._Cities = base.CreateQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModel>("Cities");
                }
                return this._Cities;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModel> _Cities;
        /// <summary>
        /// There are no comments for RailwayStations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RailwayStations")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModel> RailwayStations
        {
            get
            {
                if ((this._RailwayStations == null))
                {
                    this._RailwayStations = base.CreateQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModel>("RailwayStations");
                }
                return this._RailwayStations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModel> _RailwayStations;
        /// <summary>
        /// There are no comments for Trains in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToTrains(global::DotNextSampleApp.DotNextRZD.PublicApi.Model.TrainModel trainModel)
        {
            base.AddObject("Trains", trainModel);
        }
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCities(global::DotNextSampleApp.DotNextRZD.PublicApi.Model.CityModel cityModel)
        {
            base.AddObject("Cities", cityModel);
        }
        /// <summary>
        /// There are no comments for RailwayStations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToRailwayStations(global::DotNextSampleApp.DotNextRZD.PublicApi.Model.RailwayStationModel railwayStationModel)
        {
            base.AddObject("RailwayStations", railwayStationModel);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""DotNextRZD.PublicApi.Model"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""TrainModel"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""TrainNumber"" Type=""Edm.String"" />
        <Property Name=""OriginRailwayStationId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""OriginRailwayStationName"" Type=""Edm.String"" />
        <Property Name=""DestinationRailwayStationId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""DestinationRailwayStationName"" Type=""Edm.String"" />
        <Property Name=""ScheduledTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""CurrentTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""StatusCode"" Type=""Edm.String"" />
        <Property Name=""Status"" Type=""Edm.String"" />
        <Property Name=""UpdatedStatus"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""IsDelayed"" Type=""Edm.Boolean"" />
      </EntityType>
      <EntityType Name=""CityModel"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Latitude"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""Longitude"" Type=""Edm.Decimal"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""RailwayStationModel"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Code"" Type=""Edm.String"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""CityId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Latitude"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""Longitude"" Type=""Edm.Decimal"" Nullable=""false"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Trains"" EntityType=""DotNextRZD.PublicApi.Model.TrainModel"" />
        <EntitySet Name=""Cities"" EntityType=""DotNextRZD.PublicApi.Model.CityModel"" />
        <EntitySet Name=""RailwayStations"" EntityType=""DotNextRZD.PublicApi.Model.RailwayStationModel"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
